
# KGH Employee Payslip Reports

import kg_emp_sal_muster
import kg_emp_bank_stm
import kg_bank_list
import kg_pf_paymuster
import kg_otdays
import kg_pay_abstract
import kg_nonpf_paymuster
import kg_netpayment
import kg_banklist_text_report
#import kg_allowance_report
import kg_emp_bouns
import kg_emp_bouns_pdf
import kg_baask_sal_muster
import customer_report
import kg_leave_balance_rep
import kg_employee_history_report
#import kg_cumul_ded_report
import kg_wh_emp_sal_muster
import kg_emp_payslip_rpt	
import onscreen_salary_muster
import onscreen_emp_payslip



