# KG Store Reports

import grn_register_report
import dep_issue_register
import store_issue_slip
import pobill_from_store2_po
import dep_indent_to_issue
import grn_to_issue
import pobill_from_po_acc
import issueslip_on_screen_report

# Store Low Proiority Reports

import issue_summary_from_mainst
import opening_stock
import new_opening_stock
import consumption_summary
import consumption_details_report
import closing_stock_report
import major_closing_stock_report
import open_stock_report
import mains_closing_stock_report
import kg_depindent_detail_report
import kg_pi_detail_report
